baseURL: "https://tehlug.org/"
languageCode: "fa-ir"
title: "تهران‌لاگ"
theme: "Tehlug-Hugo-Theme"
paginate: 3
favicon: static/favicon.ico

params:
  subtitle: "گروه کاربران لینوکس تهران"
  mapView: 0.002

  excludedTypes: [gallery]
  mainSections: [event, news]

  menu:
    items:
      [
        { title: "تهران‌لاگ", url: "/tehlug", name: "", name: "tehlug" },
        { title: "جلسات", url: "/events", name: "events" },
        { title: "جلسات آینده", url: "/calendar", name: "calendar" },
        { title: "اخبار", url: "/news", name: "news" },
        { title: "موضوعات", url: "/topics", name: "topics" },
        { title: "ارائه دهندگان", url: "/speakers", name: "speakers" },
        { title: "تصاویر", url: "/images", name: "images" },
      ]

  footer:
    items:
      [
        { title: "پرسش‌های پر تکرار", url: "/faq" },
        { title: "لیست پستی", url: "/maillist" },
        { title: "لاگ‌های دیگر", url: "https://lugs.ir/" },
        { title: "آرشیو", url: "https://archive.org/details/@tehlug" },
        { title: "گیت‌هاب", url: "https://github.com/tehlug" },
        { title: "ترلو", url: "https://trello.com/tehlug" },
        { title: "گفت‌وگوی زنده", url: "irc://irc.freenode.org/tehlug" },
        { title: "تلگرام", url: "https://t.me/TehranLUG" },
        { title: "ماستادون", url: "https://mastodon.social/@tehlug/" },
        { title: "توییتر", url: "https://twitter.com/tehlug" },
        { title: "اینستاگرام", url: "https://instagram.com/tehlug" },
        { title: "ایوند", url: "https://evand.com/tehlug" },
      ]

taxonomies:
  topics: "topics"
  speakers: "speakers"
  locations: "locations"
  participants: "participants"
